# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [24]:


def nearest_value(given_value, array):
    array = np.array(array)
    idx = (np.abs(array - given_value)).argmin()
    value = array[idx]
    return value

given_value = 7
array = [3, 5, 10, 13, 19]
myValue = nearest_value(given_value, array)
print("The nearest value to", given_value, "in the array is:", myValue)


The nearest value to 7 in the array is: 5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [13]:
def sum_with_iterator(array1, array2):
    if array1.shape != (1, 3) or array2.shape != (3, 1):
        raise ValueError("Input arrays must have shapes (1, 3) and (3, 1) respectively.")
    
    result = 0
    for row in array1:
        for col in array2:
            result += row * col

    return result


array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])
sum_result = sum_with_iterator(array1, array2)
print("Sum of the two arrays:", sum_result)

Sum of the two arrays: [15 30 45]


#### 63. Create an array class that has a name attribute (★★☆)

In [31]:


class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj


data = [1, 2, 3, 4, 5]
name = "Array Name"
my_array = NamedArray(data, name=name)

print(my_array)
print("Name of the array:", my_array.name)


[1 2 3 4 5]
Name of the array: Array Name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [32]:

def add_one_at_indices(original_vector, indices_to_add_one):
    unique_indices, counts = np.unique(indices_to_add_one, return_counts=True)

    result_vector = np.copy(original_vector)
    result_vector[unique_indices] += counts

    return result_vector

given_vector = np.array([10, 20, 30, 40, 50])
indices_to_add_one = np.array([0, 1, 3, 3, 4])

result_vector = add_one_at_indices(given_vector, indices_to_add_one)
print("Original Vector:", given_vector)
print("Result Vector:", result_vector)


Original Vector: [10 20 30 40 50]
Result Vector: [11 21 30 42 51]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [33]:


def accumulate_by_indices(X, I, F):
    np.add.at(F, I, X)

X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 3, 3, 4])
F = np.zeros(5, dtype=np.int32)

accumulate_by_indices(X, I, F)

print("X:", X)
print("F:", F)


X: [1 2 3 4 5]
F: [1 2 0 7 5]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [45]:
def count_unique_colors(image):


  flattened_image = image.reshape(-1, 3)
  unique_colors = np.unique(flattened_image)
  return len(unique_colors)

if __name__ == "__main__":
  image = np.random.randint(0, 255, (16, 16, 3)).astype(np.ubyte)
  number_of_unique_colors = count_unique_colors(image)
  print("Number of unique colors in the image:", number_of_unique_colors)

Number of unique colors in the image: 241


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [46]:
def sum_last_two_axis(array):

  return np.sum(array, axis=(2, 3))

if __name__ == "__main__":
  array = np.random.randint(0, 255, (16, 16, 8, 8))
  summed_array = sum_last_two_axis(array)
  print('Sum of array: ', summed_array)

Sum of array:  [[6915 8632 7283 8403 8512 8063 8547 9027 7566 8019 8584 7391 8064 8768
  7969 8512]
 [8343 8062 8571 7523 7918 8127 7875 8474 8356 7380 7967 8101 8496 8242
  7869 7691]
 [8276 6912 8679 8550 7972 6963 8596 8254 8749 7227 8316 8547 7969 9129
  8129 8324]
 [8493 7441 8835 7612 8003 7128 7588 8635 8434 8609 7430 8650 7200 8379
  8741 7817]
 [8198 8789 8501 8113 7981 8486 8028 7641 8876 7891 8480 8198 8360 7811
  6789 8324]
 [8709 7899 8433 7213 8601 9006 8541 8361 8543 7034 7837 7967 7844 8737
  7743 7323]
 [8598 8733 7558 8947 8222 6443 8245 7602 7834 8554 8213 8104 7990 9646
  8326 8107]
 [6740 8625 9110 8010 8447 7843 7979 8132 8301 8751 8136 8617 7862 8753
  7548 9724]
 [7682 8212 7563 8166 9143 8174 8290 8419 8749 8684 8245 7021 8146 8143
  9080 8500]
 [8774 8482 8416 8187 7883 8385 7892 8126 9067 8620 7725 8715 7016 8340
  8204 7694]
 [7969 8396 9080 8095 8512 7811 9529 9067 7943 8736 8247 8240 8170 8051
  8167 7906]
 [7190 8654 8922 8107 7932 8679 8404 7646 7965 822

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [48]:
def compute_subset_means(D, S):
    unique_indices = np.unique(S)
    subset_sums = np.bincount(S, weights=D)
    subset_counts = np.bincount(S)
    subset_means = subset_sums / subset_counts
    return subset_means[unique_indices]

D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

subset_means = compute_subset_means(D, S)
print("Subset means:", subset_means)

Subset means: [2.  5.  8.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [56]:
def get_diagonal_dot_product(matrix1, matrix2):
    dot_product_matrix = np.dot(matrix1, matrix2)
    diagonal = np.diagonal(dot_product_matrix)
    return diagonal


matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

diagonal_dot_product = get_diagonal_dot_product(matrix1, matrix2)
print("Diagonal of the dot product:", diagonal_dot_product)

Diagonal of the dot product: [ 58 154]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [64]:
import numpy as np

def interleave_zeros(vector):
 
  new_vector = np.zeros(len(vector) * 6)
  index = 0
  for value in vector:
    new_vector[index] = value
    index += 1
    for _ in range(3):
      new_vector[index] = 0
      index += 1
  return new_vector

if __name__ == "__main__":
  vector = np.array([1, 2, 3, 4, 5, 6, 7])
  new_vector = interleave_zeros(vector)
  print(new_vector)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0. 6. 0. 0. 0.
 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [65]:


def multiply_arrays(array1, array2):
 
  new_array = np.zeros((5, 5))
  for i in range(5):
    for j in range(5):
      for k in range(3):
        new_array[i, j] += array1[i, j, k] * array2[i, j]
  return new_array

if __name__ == "__main__":
  array1 = np.random.randint(0, 10, (5, 5, 3))
  array2 = np.random.randint(0, 10, (5, 5))
  new_array = multiply_arrays(array1, array2)
  print(new_array)


[[ 45.  36. 102. 100.  18.]
 [ 18. 136.  91.  78.  38.]
 [ 10. 108.  18. 104.  18.]
 [  0.  99.  40.  85.  90.]
 [ 17. 120. 133.  12. 114.]]


#### 72. How to swap two rows of an array? (★★★)

In [66]:
def swap_rows(array, row1, row2):

  temp = array[row1, :]
  array[row1, :] = array[row2, :]
  array[row2, :] = temp
  return array

if __name__ == "__main__":
  array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  new_array = swap_rows(array, 0, 2)
  print(new_array)

[[7 8 9]
 [4 5 6]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [67]:
def find_unique_line_segments(triangles):
  
  line_segments = set()
  for triangle in triangles:
    for i in range(3):
      for j in range(i + 1, 3):
        line_segments.add((triangle[i], triangle[j]))
  return line_segments

if __name__ == "__main__":
  triangles = [[0, 1, 2], [0, 2, 3], [1, 2, 3], [0, 3, 1], [1, 3, 2], [2, 3, 0]]
  unique_line_segments = find_unique_line_segments(triangles)
  print(unique_line_segments)


{(0, 1), (1, 2), (3, 1), (0, 3), (2, 0), (3, 0), (2, 3), (0, 2), (3, 2), (1, 3)}


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [68]:

def produce_array_from_bincount(c):

  a = np.zeros(c[-1] + 1, dtype=int)
  for i in range(len(c)):
    a[c[i]] = i
  return a

if __name__ == "__main__":
  c = np.array([1, 2, 3, 4, 5])
  a = produce_array_from_bincount(c)
  print(a)


[0 0 1 2 3 4]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [69]:

def compute_moving_averages(array, window_size):
  
  moving_averages = np.zeros(len(array) - window_size + 1)
  for i in range(len(moving_averages)):
    moving_averages[i] = np.mean(array[i:i + window_size])
  return moving_averages

if __name__ == "__main__":
  array = np.random.randint(0, 100, 100)
  moving_averages = compute_moving_averages(array, 5)
  print(moving_averages)


[53.6 45.6 42.4 31.2 34.8 39.6 57.  61.8 72.6 57.6 52.6 42.4 36.4 40.6
 45.4 63.2 55.8 52.  54.  61.  46.2 61.8 54.4 40.2 39.6 51.6 37.8 54.4
 58.8 57.4 55.  66.8 68.2 68.4 69.6 68.4 66.8 50.2 46.4 47.2 38.  32.2
 35.  35.4 35.2 35.4 41.6 53.6 59.  51.2 60.  58.8 51.2 46.6 55.6 49.2
 37.4 29.4 42.2 38.6 33.8 49.  54.2 52.4 58.8 69.  69.2 69.2 69.6 53.2
 56.4 45.  56.6 54.  68.  62.2 68.6 65.4 51.4 46.  50.4 47.6 38.  41.8
 33.2 28.  27.6 33.6 32.2 40.8 46.8 40.  37.2 45.6 38.4 25.2]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [70]:

def create_shifted_array(z):


  array_shape = (len(z) // 3, 3)
  array = np.zeros(array_shape, dtype=z.dtype)
  for i in range(array.shape[0]):
    array[i] = z[i * 3:(i + 1) * 3]
  return array

if __name__ == "__main__":
  z = np.arange(9)
  shifted_array = create_shifted_array(z)
  print(shifted_array)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [71]:
def negate_boolean_inplace(boolean):
  boolean = ~boolean

def change_sign_of_float_inplace(float_number):
  float_number = -float_number

if __name__ == "__main__":
  boolean = True
  negate_boolean_inplace(boolean)
  print(boolean)

  float_number = 1.0
  change_sign_of_float_inplace(float_number)
  print(float_number)

True
1.0


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [78]:

def distance_to_lines(P0, P1, p):
    x0, y0 = p
    x1, y1 = P0.T
    x2, y2 = P1.T

    numerator = np.abs((x2 - x1) * (y1 - y0) - (x1 - x0) * (y2 - y1))
    denominator = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

    distances = numerator / denominator
    return distances


P0 = np.array([[1, 2], [3, 4], [5, 6]])  # First points of the lines
P1 = np.array([[7, 8], [9, 10], [11, 12]])  # Second points of the lines
p = np.array([13, 14])  # The point 'p'

distances = distance_to_lines(P0, P1, p)
print("Distances to lines:", distances)


Distances to lines: [0. 0. 0.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [80]:
def distance_to_lines(P0, P1, p):
    x0, y0 = p
    x1, y1 = P0.T
    x2, y2 = P1.T

    numerator = np.abs((x2 - x1) * (y1 - y0) - (x1 - x0) * (y2 - y1))
    denominator = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

    distances = numerator / denominator
    return distances


P0 = np.array([[1, 2], [3, 4], [5, 6]])  # First points of the lines
P1 = np.array([[7, 8], [9, 10], [11, 12]])  # Second points of the lines
p = np.array([13, 14])  # The point 'p'

distances = distance_to_lines(P0, P1, p)
print("Distances to lines:", distances)


Distances to lines: [0. 0. 0.]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [81]:
def extract_subpart_centered_on_element(array, shape, fill_value=0):

  center = np.array(shape) // 2
  start = center - np.array(array.shape) // 2
  end = start + shape
  subpart = np.full(shape, fill_value)
  subpart[start[0]:end[0], start[1]:end[1]] = array[
      center[0] - start[0]:center[0] + end[0],
      center[1] - start[1]:center[1] + end[1]]
  return subpart


if __name__ == "__main__":
  array = np.arange(16).reshape((4, 4))
  subpart = extract_subpart_centered_on_element(array, (3, 3), fill_value=-1)
  print(subpart)

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [82]:
def generate_array_from_z(z):

  r = []
  for i in range(len(z) // 4):
    r.append(z[i * 4:(i + 1) * 4])
  return r


if __name__ == "__main__":
  z = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
  r = generate_array_from_z(z)
  print(r)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


#### 82. Compute a matrix rank (★★★)

In [85]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix:")
print(matrix)
print("Rank of the matrix:", rank)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [86]:
def most_frequent_value(array):
    counts = np.bincount(array)
    most_frequent = np.argmax(counts)
    return most_frequent

arr = np.array([1, 2, 3, 2, 2, 3, 4, 3, 3, 3, 4, 4, 4, 4])
most_frequent_val = most_frequent_value(arr)
print("Most frequent value in the array:", most_frequent_val)

Most frequent value in the array: 3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [87]:
def extract_contiguous_blocks(matrix):
    block_size = 3
    blocks = []
    rows, cols = matrix.shape

    for r in range(rows - block_size + 1):
        for c in range(cols - block_size + 1):
            block = matrix[r:r+block_size, c:c+block_size]
            blocks.append(block)

    return blocks

np.random.seed(42)  # For reproducibility
matrix = np.random.randint(0, 100, size=(10, 10))

blocks = extract_contiguous_blocks(matrix)

# Print the extracted blocks
for i, block in enumerate(blocks):
    print(f"Block {i + 1}:")
    print(block)
    print()

Block 1:
[[51 92 14]
 [87 99 23]
 [ 1 63 59]]

Block 2:
[[92 14 71]
 [99 23  2]
 [63 59 20]]

Block 3:
[[14 71 60]
 [23  2 21]
 [59 20 32]]

Block 4:
[[71 60 20]
 [ 2 21 52]
 [20 32 75]]

Block 5:
[[60 20 82]
 [21 52  1]
 [32 75 57]]

Block 6:
[[20 82 86]
 [52  1 87]
 [75 57 21]]

Block 7:
[[82 86 74]
 [ 1 87 29]
 [57 21 88]]

Block 8:
[[86 74 74]
 [87 29 37]
 [21 88 48]]

Block 9:
[[87 99 23]
 [ 1 63 59]
 [90 58 41]]

Block 10:
[[99 23  2]
 [63 59 20]
 [58 41 91]]

Block 11:
[[23  2 21]
 [59 20 32]
 [41 91 59]]

Block 12:
[[ 2 21 52]
 [20 32 75]
 [91 59 79]]

Block 13:
[[21 52  1]
 [32 75 57]
 [59 79 14]]

Block 14:
[[52  1 87]
 [75 57 21]
 [79 14 61]]

Block 15:
[[ 1 87 29]
 [57 21 88]
 [14 61 61]]

Block 16:
[[87 29 37]
 [21 88 48]
 [61 61 46]]

Block 17:
[[ 1 63 59]
 [90 58 41]
 [61 50 54]]

Block 18:
[[63 59 20]
 [58 41 91]
 [50 54 63]]

Block 19:
[[59 20 32]
 [41 91 59]
 [54 63  2]]

Block 20:
[[20 32 75]
 [91 59 79]
 [63  2 50]]

Block 21:
[[32 75 57]
 [59 79 14]
 [ 2 50  6]]

B

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [88]:

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __setitem__(self, key, value):
        i, j = key
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

    def __getitem__(self, key):
        i, j = key
        return super(SymmetricArray, self).__getitem__((i, j))

data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

symmetric_array = SymmetricArray(data)
print("Original Array:")
print(symmetric_array)

# Modify an element, and both [i, j] and [j, i] are updated
symmetric_array[1, 2] = 99

print("\nModified Array:")
print(symmetric_array)

# Access elements, and both [i, j] and [j, i] return the same value
print("\nAccessing elements:")
print(symmetric_array[1, 2])
print(symmetric_array[2, 1])


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified Array:
[[ 1  2  3]
 [ 4  5 99]
 [ 7 99  9]]

Accessing elements:
99
99


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [92]:
import numpy as np

def compute_sum_of_matrix_products(matrices, vectors):
 

  sum_of_products = np.zeros((matrices[0].shape[0], 1))
  for matrix, vector in zip(matrices, vectors):
    sum_of_products += matrix @ vector
  return sum_of_products


if __name__ == "__main__":
  matrices = np.array([
      np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])
  ])
  vectors = np.array([
      np.array([[1], [2]]), np.array([[3], [4]]), np.array([[5], [6]])
  ])
  sum_of_products = compute_sum_of_matrix_products(matrices, vectors)
  assert sum_of_products.shape == (2, 1)
print("Sum of matrix products:")
print(sum_of_products)

Sum of matrix products:
[[149.]
 [191.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [94]:

def get_block_sum(array):


  block_size = 4
  block_sum = np.zeros((array.shape[0] // block_size, array.shape[1] // block_size))
  for i in range(block_sum.shape[0]):
    for j in range(block_sum.shape[1]):
      block_sum[i, j] = np.sum(array[i * block_size:(i + 1) * block_size,
                                       j * block_size:(j + 1) * block_size])
  return block_sum


if __name__ == "__main__":
  array = np.arange(256).reshape((16, 16))
  block_sum = get_block_sum(array)
  assert block_sum.shape == (4, 4)
print(block_sum)

[[ 408.  472.  536.  600.]
 [1432. 1496. 1560. 1624.]
 [2456. 2520. 2584. 2648.]
 [3480. 3544. 3608. 3672.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [114]:

def game_of_life(grid, steps=1):
    for step in range(steps):
        new_grid = np.copy(grid)

        neighbors_count = (
            grid[:-2, :-2] + grid[:-2, 1:-1] + grid[:-2, 2:] +
            grid[1:-1, :-2] + grid[1:-1, 2:] +
            grid[2:, :-2] + grid[2:, 1:-1] + grid[2:, 2:]
        )

        new_grid[1:-1, 1:-1][(grid[1:-1, 1:-1] == 1) & ((neighbors_count < 2) | (neighbors_count > 3))] = 0
        new_grid[1:-1, 1:-1][(grid[1:-1, 1:-1] == 0) & (neighbors_count == 3)] = 1

        grid = new_grid

    return grid

grid_size = 10
initial_grid = np.random.randint(2, size=(grid_size, grid_size))

num_steps = 10
final_grid = game_of_life(initial_grid, steps=num_steps)

print("Final Grid:")
print(final_grid)


Final Grid:
[[1 0 1 1 0 0 0 1 0 1]
 [1 0 0 0 0 0 1 1 0 1]
 [0 1 1 1 0 0 1 1 0 1]
 [1 0 0 1 0 0 0 0 0 1]
 [0 1 1 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 0 1]
 [0 1 1 0 1 0 0 1 0 1]
 [1 1 0 0 0 1 0 1 0 1]
 [1 1 0 0 1 1 0 1 1 1]]


#### 89. How to get the n largest values of an array (★★★)

In [115]:

def n_largest_values(array, n):
    indices_sorted = np.argsort(array)
    n_largest_indices = indices_sorted[-n:]
    n_largest_values = array[n_largest_indices]
    return n_largest_values

arr = np.array([5, 2, 9, 1, 7, 6, 8, 3, 4])
n = 3

n_largest = n_largest_values(arr, n)
print("The", n, "largest values:", n_largest)


The 3 largest values: [7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [116]:
import itertools

def cartesian_product(*vectors):
    return list(itertools.product(*vectors))

vec1 = [1, 2]
vec2 = ['a', 'b', 'c']
vec3 = [True, False]

result = cartesian_product(vec1, vec2, vec3)
print("Cartesian product:")
print(result)


Cartesian product:
[(1, 'a', True), (1, 'a', False), (1, 'b', True), (1, 'b', False), (1, 'c', True), (1, 'c', False), (2, 'a', True), (2, 'a', False), (2, 'b', True), (2, 'b', False), (2, 'c', True), (2, 'c', False)]


#### 91. How to create a record array from a regular array? (★★★)

In [117]:
regular_array = np.array([[1, 'Alice', 30],
                          [2, 'Bob', 25],
                          [3, 'Charlie', 40]])

field_names = ['ID', 'Name', 'Age']
record_array = np.rec.fromarrays(regular_array.T, names=field_names)

print("Record array:")
print(record_array)
print("Access elements using field names:")
print(record_array['ID'])
print(record_array['Name'])
print(record_array['Age'])

Record array:
[('1', 'Alice', '30') ('2', 'Bob', '25') ('3', 'Charlie', '40')]
Access elements using field names:
['1' '2' '3']
['Alice' 'Bob' 'Charlie']
['30' '25' '40']


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [120]:
Z = np.random.rand(1000000)  
Z_power_3 = np.power(Z, 3)

print(Z_power_3)

[0.50331352 0.79705649 0.01291867 ... 0.05180405 0.00512584 0.07415503]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [122]:

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [2, 3, 1],
              [7, 8, 9],
              [3, 2, 1],
              [6, 5, 4],
              [1, 2, 3],
              [9, 8, 7]])

B = np.array([[1, 2],
              [2, 3]])

rows_with_elements_of_B = np.all(np.isin(A, B), axis=1)

result_indices = np.where(rows_with_elements_of_B)[0]

result_rows = A[result_indices]

print("Result Rows:")
print(result_rows)


Result Rows:
[[1 2 3]
 [2 3 1]
 [3 2 1]
 [1 2 3]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [124]:

matrix = np.array([[1, 1, 1],
                   [2, 2, 2],
                   [3, 3, 3],
                   [2, 2, 3],
                   [4, 4, 4],
                   [5, 5, 5],
                   [3, 3, 3],
                   [6, 6, 6],
                   [7, 7, 7],
                   [8, 8, 8]])

mask = np.any(matrix != matrix[:, [0]], axis=1)

result_rows = matrix[mask]

print("Rows with unequal values:")
print(result_rows)


Rows with unequal values:
[[2 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [126]:

def int_to_binary_matrix(vector, num_bits):
    mask = 1 << np.arange(num_bits)

    binary_matrix = (vector[:, None] & mask) > 0

    return binary_matrix.astype(int)

vector = np.array([5, 3, 7, 2, 9])
num_bits = 4  
binary_matrix = int_to_binary_matrix(vector, num_bits)
print("Binary Matrix:")
print(binary_matrix)


Binary Matrix:
[[1 0 1 0]
 [1 1 0 0]
 [1 1 1 0]
 [0 1 0 0]
 [1 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [127]:

def extract_unique_rows(array):
    unique_rows, indices = np.unique(array, axis=0, return_index=True)
    return unique_rows

two_dimensional_array = np.array([[1, 2, 3],
                                 [4, 5, 6],
                                 [1, 2, 3],
                                 [7, 8, 9],
                                 [4, 5, 6]])

unique_rows = extract_unique_rows(two_dimensional_array)
print("Unique Rows:")
print(unique_rows)


Unique Rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [131]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

inner_product = np.einsum('i,i', A, B)

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

outer_product = np.einsum('i,j->ij', A, B)
A = np.array([1, 2, 3, 4])

sum_result = np.einsum('i', A)

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

mul_result = np.einsum('i,i->i', A, B)

print("Inner product:", inner_product)
print("Outer product:", outer_product)
print("Sum:", sum_result)
print("Element-wise multiplication:", mul_result)

Inner product: 32
Outer product: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum: [1 2 3 4]
Element-wise multiplication: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [134]:


def sample_path_equidistant(X, Y, num_samples):
    total_distance = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
    total_distance = np.insert(total_distance, 0, 0) 
    total_distance /= total_distance[-1]

    equidistant_samples = np.linspace(0, 1, num_samples)

    X_sampled = np.interp(equidistant_samples, total_distance, X)
    Y_sampled = np.interp(equidistant_samples, total_distance, Y)

    return X_sampled, Y_sampled

X = np.array([0, 1, 3, 6, 8])
Y = np.array([0, 2, 4, 7, 9])

num_samples = 10
X_sampled, Y_sampled = sample_path_equidistant(X, Y, num_samples)
print("Sampled X:", X_sampled)
print("Sampled Y:", Y_sampled)


Sampled X: [0.         0.60302097 1.32578091 2.27924078 3.23270065 4.18616052
 5.13962039 6.09308026 7.04654013 8.        ]
Sampled Y: [0.         1.20604194 2.32578091 3.27924078 4.23270065 5.18616052
 6.13962039 7.09308026 8.04654013 9.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [144]:
import numpy as np

def select_multinomial_rows(X, n):
    is_integer = np.all(X.astype(int) == X, axis=1)
    is_sum_n = np.sum(X, axis=1) == n

    selected_rows = X[is_integer & is_sum_n]

    return selected_rows

n = 10
X = np.array([[1, 2, 7],
              [3, 4, 3],
              [0, 10, 0],
              [5, 3, 2],
              [6, 1, 3]])

selected_rows = select_multinomial_rows(X, n)
print("Selected Rows:")
print(selected_rows)


Selected Rows:
[[ 1  2  7]
 [ 3  4  3]
 [ 0 10  0]
 [ 5  3  2]
 [ 6  1  3]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [146]:

def bootstrap_confidence_intervals(X, num_samples, alpha=0.05):
    # Number of elements in the original array
    N = len(X)

    # Create an array to store the means of each bootstrap sample
    means = np.empty(num_samples)

    # Perform bootstrapping
    for i in range(num_samples):
        # Randomly sample indices with replacement
        indices = np.random.randint(0, N, N)

        # Get the bootstrap sample using the sampled indices
        bootstrap_sample = X[indices]

        # Calculate the mean of the bootstrap sample
        means[i] = np.mean(bootstrap_sample)

    # Calculate the lower and upper percentiles for the confidence intervals
    lower_percentile = (alpha / 2) * 100
    upper_percentile = (1 - alpha / 2) * 100

    # Compute the confidence intervals
    confidence_interval_lower = np.percentile(means, lower_percentile)
    confidence_interval_upper = np.percentile(means, upper_percentile)

    return confidence_interval_lower, confidence_interval_upper

X = np.array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

num_samples = 1000
alpha = 0.05

lower, upper = bootstrap_confidence_intervals(X, num_samples, alpha)
print("Bootstrapped 95% Confidence Intervals:")
print("Lower:", lower)
print("Upper:", upper)


Bootstrapped 95% Confidence Intervals:
Lower: 15.795000000000002
Upper: 22.8
