# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [24]:


def nearest_value(given_value, array):
    array = np.array(array)
    idx = (np.abs(array - given_value)).argmin()
    value = array[idx]
    return value

given_value = 7
array = [3, 5, 10, 13, 19]
myValue = nearest_value(given_value, array)
print("The nearest value to", given_value, "in the array is:", myValue)


The nearest value to 7 in the array is: 5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [13]:
def sum_with_iterator(array1, array2):
    if array1.shape != (1, 3) or array2.shape != (3, 1):
        raise ValueError("Input arrays must have shapes (1, 3) and (3, 1) respectively.")
    
    result = 0
    for row in array1:
        for col in array2:
            result += row * col

    return result


array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])
sum_result = sum_with_iterator(array1, array2)
print("Sum of the two arrays:", sum_result)

Sum of the two arrays: [15 30 45]


#### 63. Create an array class that has a name attribute (★★☆)

In [31]:


class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj


data = [1, 2, 3, 4, 5]
name = "Array Name"
my_array = NamedArray(data, name=name)

print(my_array)
print("Name of the array:", my_array.name)


[1 2 3 4 5]
Name of the array: Array Name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [32]:

def add_one_at_indices(original_vector, indices_to_add_one):
    unique_indices, counts = np.unique(indices_to_add_one, return_counts=True)

    result_vector = np.copy(original_vector)
    result_vector[unique_indices] += counts

    return result_vector

given_vector = np.array([10, 20, 30, 40, 50])
indices_to_add_one = np.array([0, 1, 3, 3, 4])

result_vector = add_one_at_indices(given_vector, indices_to_add_one)
print("Original Vector:", given_vector)
print("Result Vector:", result_vector)


Original Vector: [10 20 30 40 50]
Result Vector: [11 21 30 42 51]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [33]:


def accumulate_by_indices(X, I, F):
    np.add.at(F, I, X)

X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 3, 3, 4])
F = np.zeros(5, dtype=np.int32)

accumulate_by_indices(X, I, F)

print("X:", X)
print("F:", F)


X: [1 2 3 4 5]
F: [1 2 0 7 5]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [45]:
def count_unique_colors(image):


  flattened_image = image.reshape(-1, 3)
  unique_colors = np.unique(flattened_image)
  return len(unique_colors)

if __name__ == "__main__":
  image = np.random.randint(0, 255, (16, 16, 3)).astype(np.ubyte)
  number_of_unique_colors = count_unique_colors(image)
  print("Number of unique colors in the image:", number_of_unique_colors)

Number of unique colors in the image: 241


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [46]:
def sum_last_two_axis(array):

  return np.sum(array, axis=(2, 3))

if __name__ == "__main__":
  array = np.random.randint(0, 255, (16, 16, 8, 8))
  summed_array = sum_last_two_axis(array)
  print('Sum of array: ', summed_array)

Sum of array:  [[6915 8632 7283 8403 8512 8063 8547 9027 7566 8019 8584 7391 8064 8768
  7969 8512]
 [8343 8062 8571 7523 7918 8127 7875 8474 8356 7380 7967 8101 8496 8242
  7869 7691]
 [8276 6912 8679 8550 7972 6963 8596 8254 8749 7227 8316 8547 7969 9129
  8129 8324]
 [8493 7441 8835 7612 8003 7128 7588 8635 8434 8609 7430 8650 7200 8379
  8741 7817]
 [8198 8789 8501 8113 7981 8486 8028 7641 8876 7891 8480 8198 8360 7811
  6789 8324]
 [8709 7899 8433 7213 8601 9006 8541 8361 8543 7034 7837 7967 7844 8737
  7743 7323]
 [8598 8733 7558 8947 8222 6443 8245 7602 7834 8554 8213 8104 7990 9646
  8326 8107]
 [6740 8625 9110 8010 8447 7843 7979 8132 8301 8751 8136 8617 7862 8753
  7548 9724]
 [7682 8212 7563 8166 9143 8174 8290 8419 8749 8684 8245 7021 8146 8143
  9080 8500]
 [8774 8482 8416 8187 7883 8385 7892 8126 9067 8620 7725 8715 7016 8340
  8204 7694]
 [7969 8396 9080 8095 8512 7811 9529 9067 7943 8736 8247 8240 8170 8051
  8167 7906]
 [7190 8654 8922 8107 7932 8679 8404 7646 7965 822

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [48]:
def compute_subset_means(D, S):
    unique_indices = np.unique(S)
    subset_sums = np.bincount(S, weights=D)
    subset_counts = np.bincount(S)
    subset_means = subset_sums / subset_counts
    return subset_means[unique_indices]

D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

subset_means = compute_subset_means(D, S)
print("Subset means:", subset_means)

Subset means: [2.  5.  8.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [56]:
def get_diagonal_dot_product(matrix1, matrix2):
    dot_product_matrix = np.dot(matrix1, matrix2)
    diagonal = np.diagonal(dot_product_matrix)
    return diagonal


matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

diagonal_dot_product = get_diagonal_dot_product(matrix1, matrix2)
print("Diagonal of the dot product:", diagonal_dot_product)

Diagonal of the dot product: [ 58 154]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [64]:
import numpy as np

def interleave_zeros(vector):
 
  new_vector = np.zeros(len(vector) * 6)
  index = 0
  for value in vector:
    new_vector[index] = value
    index += 1
    for _ in range(3):
      new_vector[index] = 0
      index += 1
  return new_vector

if __name__ == "__main__":
  vector = np.array([1, 2, 3, 4, 5, 6, 7])
  new_vector = interleave_zeros(vector)
  print(new_vector)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0. 6. 0. 0. 0.
 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [65]:


def multiply_arrays(array1, array2):
 
  new_array = np.zeros((5, 5))
  for i in range(5):
    for j in range(5):
      for k in range(3):
        new_array[i, j] += array1[i, j, k] * array2[i, j]
  return new_array

if __name__ == "__main__":
  array1 = np.random.randint(0, 10, (5, 5, 3))
  array2 = np.random.randint(0, 10, (5, 5))
  new_array = multiply_arrays(array1, array2)
  print(new_array)


[[ 45.  36. 102. 100.  18.]
 [ 18. 136.  91.  78.  38.]
 [ 10. 108.  18. 104.  18.]
 [  0.  99.  40.  85.  90.]
 [ 17. 120. 133.  12. 114.]]


#### 72. How to swap two rows of an array? (★★★)

In [66]:
def swap_rows(array, row1, row2):

  temp = array[row1, :]
  array[row1, :] = array[row2, :]
  array[row2, :] = temp
  return array

if __name__ == "__main__":
  array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  new_array = swap_rows(array, 0, 2)
  print(new_array)

[[7 8 9]
 [4 5 6]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [67]:
def find_unique_line_segments(triangles):
  
  line_segments = set()
  for triangle in triangles:
    for i in range(3):
      for j in range(i + 1, 3):
        line_segments.add((triangle[i], triangle[j]))
  return line_segments

if __name__ == "__main__":
  triangles = [[0, 1, 2], [0, 2, 3], [1, 2, 3], [0, 3, 1], [1, 3, 2], [2, 3, 0]]
  unique_line_segments = find_unique_line_segments(triangles)
  print(unique_line_segments)


{(0, 1), (1, 2), (3, 1), (0, 3), (2, 0), (3, 0), (2, 3), (0, 2), (3, 2), (1, 3)}


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)